export const named = {
  jetBlack: "#363230",
  davysGrey: "#4A4845",
  davysGreyTransparent: "rgba(74, 72, 69, 0.6)",
  indigoDye: '#204E6F',
  indigoDyeTransparent: "rgba(32, 78, 111, 0.6)",
  steelBlue: "#3581b8",
  amazonGreen: "#537a5a",
  mintCream: "#f3f8f2",
  mintCreamTransparent: "rgba(243, 248, 242, 0.8)",
  alabasterLight: "#e9ede4",
  alabaster: "#dee2d6",
  artichoke: "#9DA391",
  artichokeTransparent: "rgba(157, 163, 145, 0.7)",
  honey: "#fdb833",
  orange: "#f4743b",
  princeton: "#FA8638",
  macaroni: "#fcb07e"
}

export default {
  primary: named.steelBlue,
  primaryDark: named.indigoDye,
  primaryDarkTransparent: named.indigoDyeTransparent,
  secondary: named.davysGrey,
  secondaryExtraLight: named.alabasterLight,
  secondaryLight: named.alabaster,
  secondaryMedium: named.artichoke,
  success: named.amazonGreen,
  successTransparent: named.artichokeTransparent,
  info: named.macaroni,
  infoDark: named.princeton,
  warning: named.honey,
  danger: named.orange,
  submit: named.steelBlue,
  option: named.amazonGreen,
  cancel: named.macaroni,
  black: named.jetBlack,
  grey: named.davysGrey,
  greyTransparent: named.davysGreyTransparent,
  white: named.mintCream,
  transparentWhite: named.mintCreamTransparent,
}

